export const ADD_ONE = 'ADD_ONE';
export const REMOVE_ONE = 'REMOVE_ONE';
export const RESET_QUANTITY = 'RESET_QUANTITY';
export const HANDLE_QUANTITY = 'HANDLE_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const TOOGLE_CART = 'TOOGLE_CART';

export const TOOGLE_MODAL = 'TOOGLE_MODAL';

export const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED';
export const FETCH_PRODUCTS_SUCCEDED = 'FETCH_PRODUCTS_SUCCEDED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_PRODUCT_REQUESTED = 'FETCH_PRODUCT_REQUESTED';
export const FETCH_PRODUCT_SUCCEDED = 'FETCH_PRODUCT_SUCCEDED';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
